# Config
CONFIG += c++14 warn_on

#C++ Flags
QMAKE_CXXFLAGS += -pedantic
QMAKE_CXXFLAGS_RELEASE += -ffast-math -O3
QMAKE_CXXFLAGS_RELEASE -= -O2
QMAKE_LFLAGS_RELEASE += -flto

#DEFINES
DEFINES += QT_DEPRECATED_WARNINGS
